#!/bin/bash

# Determine current kernel version
CURRENT_KERNEL=$(uname -r)
echo "$CURRENT_KERNEL"

# Determine the kernel version of the package to be installed
NEW_KERNEL=$1
echo "$NEW_KERNEL"

# Extract major versions of kernel versions
CURRENT_MAJOR=$(echo "$CURRENT_KERNEL" | cut -d'.' -f1-2)
NEW_MAJOR=$(echo "$NEW_KERNEL" | cut -d'.' -f1-2)

# If the major versions match and the new version is higher
if [ "$CURRENT_MAJOR" = "$NEW_MAJOR" ] && [ "$NEW_KERNEL" \> "$CURRENT_KERNEL" ]; then
    # Save the kernel to be uninstalled to a file
    mkdir -p /var/local/kernel-temp
    echo "$CURRENT_KERNEL" > /var/local/kernel-temp/old_kernel_version
fi
