#!/bin/fish

# Determine current kernel version
set CURRENT_KERNEL (uname -r)

# Determine the kernel version of the package to be installe
set NEW_KERNEL (echo $DPKG_MAINTSCRIPT_PACKAGE | string split '-' -f3 )

# Determine current kernel version
set CURRENT_MAJOR (echo $CURRENT_KERNEL | string split '-' -f1 | string split '.' -f1,2 | string join '')
set NEW_MAJOR (echo $NEW_KERNEL | string split '.'  -f1,2 | string join '')
set CURRENT_MINOR (echo $CURRENT_KERNEL | string split '-' -f1 | string split '.' -f3)
set NEW_MINOR (echo $NEW_KERNEL | string split '-' -f1 | string split '.' -f3)

# If the major versions match and the new version is higher
if test $NEW_MAJOR -eq $CURRENT_MAJOR && test $NEW_MINOR -gt $CURRENT_MINOR
    # Save the kernel to be uninstalled to a file
    mkdir -p /var/local/kernel-temp
    echo $CURRENT_KERNEL > /var/local/kernel-temp/old_kernel_version
end
