#!/bin/fish

# Aktuelle Kernelversion ermitteln
set CURRENT_KERNEL (uname -r)

# Kernelversion des zu installierenden Pakets ermitteln
set NEW_KERNEL (echo $DPKG_MAINTSCRIPT_PACKAGE | string split '-' -f3 )

# Kernelversionen extrahieren
set CURRENT_MAJOR (echo $CURRENT_KERNEL | string split '-' -f1 | string split '.' -f1,2 | string join '')
set NEW_MAJOR (echo $NEW_KERNEL | string split '.'  -f1,2 | string join '')
set CURRENT_MINOR (echo $CURRENT_KERNEL | string split '-' -f1 | string split '.' -f3)
set NEW_MINOR (echo $NEW_KERNEL | string split '-' -f1 | string split '.' -f3)

# Wenn die Hauptversionen übereinstimmen und die neue Version höher ist
if test $NEW_MAJOR -eq $CURRENT_MAJOR && test $NEW_MINOR -gt $CURRENT_MINOR
    # Den zu deinstallierenden Kernel in einer Datei speichern
    mkdir -p /var/local/kernel-temp
    echo $CURRENT_KERNEL > /var/local/kernel-temp/old_kernel_version
end
