#!/bin/fish

if test -f /var/local/kernel-temp/old_kernel_version
    set OLD_KERNEL (cat /var/local/kernel-temp/old_kernel_version)
    rm /var/local/kernel-temp/old_kernel_version

    # Determine current kernel version
    set CURRENT_KERNEL (uname -r)

    # Determine current an old kernel version
    set CURRENT_MAJOR (echo $CURRENT_KERNEL | string split '.'  -f1,2 | string join '')
    set OLD_MAJOR (echo $OLD_KERNEL | string split '.'  -f1,2 | string join '')

    # If the major versions match
    if test $CURRENT_MAJOR -eq $OLD_MAJOR
        # Remove kernel image and header
        apt-get -y purge linux-image-$OLD_KERNEL linux-headers-$OLD_KERNEL
    else
        echo The kernel to be removed has a different major version than the active kernel.
    end
end
